// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import path from "path";

// Carga el env correcto según NODE_ENV:
//   development → .env.development.local (BD local Docker)
//   production  → .env.local (Supabase)
const envFile = process.env.NODE_ENV === "production" ? ".env.local" : ".env.development.local";
config({ path: path.resolve(__dirname, envFile) });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
